### ISSUE TITLE
Error connecting to Redis

### ISSUE THREAD

**Issue by jakebrady5** [learn-co-curriculum/rails-sidekiq-readme#3]
When trying to run 'bundle exec sidekiq' I am getting a connection error.  Both sidekiq and redis are included as gems in gemfile, I updated bundler, rebundled, etc, with no luck.  Error below.

2016-03-02T03:36:27.776Z 1582 TID-owpw6l4w4 INFO: Running in ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
2016-03-02T03:36:27.776Z 1582 TID-owpw6l4w4 INFO: See LICENSE and the LGPL-3.0 for licensing details.
2016-03-02T03:36:27.776Z 1582 TID-owpw6l4w4 INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2016-03-02T03:36:27.776Z 1582 TID-owpw6l4w4 INFO: Booting Sidekiq 4.1.0 with redis options {:url=>nil}
Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
/Users/jake/.rvm/gems/ruby-2.2.3/gems/redis-3.2.2/lib/redis/client.rb:332:in `rescue in establish_connection'
/Users/jake/.rvm/gems/ruby-2.2.3/gems/redis-3.2.2/lib/redis/client.rb:318:in`establish_connection'
/Users/jake/.rvm/gems/ruby-2.2.3/gems/redis-3.2.2/lib/redis/client.rb:94:in `block in connect'
/Users/jake/.rvm/gems/ruby-2.2.3/gems/redis-3.2.2/lib/redis/client.rb:280:in`with_reconnect'
/Users/jake/.rvm/gems/ruby-2.2.3/gems/redis-3.2.2/lib/redis/client.rb:93:in `connect'
/Users/jake/.rvm/gems/ruby-2.2.3/gems/redis-3.2.2/lib/redis/client.rb:351:in`ensure_connected'
/Users/jake/.rvm/gems/ruby-2.2.3/gems/redis-3.2.2/lib/redis/client.rb:208:in `block in process'
/Users/jake/.rvm/gems/ruby-2.2.3/gems/redis-3.2.2/lib/redis/client.rb:293:in`logging'
/Users/jake/.rvm/gems/ruby-2.2.3/gems/redis-3.2.2/lib/redis/client.rb:207:in `process'
/Users/jake/.rvm/gems/ruby-2.2.3/gems/redis-3.2.2/lib/redis/client.rb:113:in`call'
/Users/jake/.rvm/gems/ruby-2.2.3/gems/redis-3.2.2/lib/redis.rb:211:in `block in info'
/Users/jake/.rvm/gems/ruby-2.2.3/gems/redis-3.2.2/lib/redis.rb:57:in`block in synchronize'
/Users/jake/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/jake/.rvm/gems/ruby-2.2.3/gems/redis-3.2.2/lib/redis.rb:57:in`synchronize'
/Users/jake/.rvm/gems/ruby-2.2.3/gems/redis-3.2.2/lib/redis.rb:210:in `info'
/Users/jake/.rvm/gems/ruby-2.2.3/gems/sidekiq-4.1.0/lib/sidekiq/cli.rb:71:in`block in run'
/Users/jake/.rvm/gems/ruby-2.2.3/gems/sidekiq-4.1.0/lib/sidekiq.rb:84:in `block in redis'
/Users/jake/.rvm/gems/ruby-2.2.3/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in`block (2 levels) in with'
/Users/jake/.rvm/gems/ruby-2.2.3/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
/Users/jake/.rvm/gems/ruby-2.2.3/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in`block in with'
/Users/jake/.rvm/gems/ruby-2.2.3/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
/Users/jake/.rvm/gems/ruby-2.2.3/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in`with'
/Users/jake/.rvm/gems/ruby-2.2.3/gems/sidekiq-4.1.0/lib/sidekiq.rb:81:in `redis'
/Users/jake/.rvm/gems/ruby-2.2.3/gems/sidekiq-4.1.0/lib/sidekiq/cli.rb:68:in`run'
/Users/jake/.rvm/gems/ruby-2.2.3/gems/sidekiq-4.1.0/bin/sidekiq:12:in `<top (required)>'
/Users/jake/.rvm/gems/ruby-2.2.3/bin/sidekiq:23:in`load'
/Users/jake/.rvm/gems/ruby-2.2.3/bin/sidekiq:23:in `<main>'
/Users/jake/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in`eval'
/Users/jake/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'

**Comment by jakebrady5** [comment]
Issue was addressed by onyoo's comment in issue #2.
